name: CI/CD

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Change directory to ECommerce.Api
      run: cd ECommerce.Api
      
    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-restore

    - name: Merge PR
      if: success()
      run: |
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git checkout dev  # Assuming your base branch is named 'dev'
        git merge --no-ff ${{ github.event.pull_request.head.ref }}
        git push origin dev
